name: Random Cron
on:
  workflow_dispatch:

jobs:
  disabled:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: disabled
        run: |
          echo "Random Cron is disabled. Scheduled runs are randomized in run.yml."
